//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public Classes()
        {
            this.Pupils = new HashSet<Pupils>();
            this.Timetable = new HashSet<Timetable>();
        }
    
        public int Code_class { get; set; }
        public string Name_class { get; set; }
        public string Class_type { get; set; }
        public Nullable<int> Number_pupils { get; set; }
        public Nullable<System.DateTime> Year_creation { get; set; }
    
        public virtual ICollection<Pupils> Pupils { get; set; }
        public virtual ICollection<Timetable> Timetable { get; set; }
    }
}
