//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Load_employee = new HashSet<Load_employee>();
            this.Timetable = new HashSet<Timetable>();
            this.Track_record = new HashSet<Track_record>();
        }
    
        public int Code_employee { get; set; }
        public string Name_employee { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Passport_details { get; set; }
        public string Education { get; set; }
    
        public virtual ICollection<Load_employee> Load_employee { get; set; }
        public virtual ICollection<Timetable> Timetable { get; set; }
        public virtual ICollection<Track_record> Track_record { get; set; }
    }
}
