//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public Lessons()
        {
            this.Load_employee = new HashSet<Load_employee>();
            this.Timetable = new HashSet<Timetable>();
        }
    
        public int Code_lesson { get; set; }
        public string Name_lessons { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Load_employee> Load_employee { get; set; }
        public virtual ICollection<Timetable> Timetable { get; set; }
    }
}
