//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load_employee
    {
        public int Code_list { get; set; }
        public int Code_lesson { get; set; }
        public int Code_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Lessons Lessons { get; set; }
    }
}
