//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolWorkEntities1 : DbContext
    {
        public SchoolWorkEntities1()
            : base("name=SchoolWorkEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Load_employee> Load_employee { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Pupils> Pupils { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<Track_record> Track_record { get; set; }
    }
}
