//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Track_record = new HashSet<Track_record>();
        }
    
        public int Code_post { get; set; }
        public string Name_post { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Duty { get; set; }
    
        public virtual ICollection<Track_record> Track_record { get; set; }
    }
}
