//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupils
    {
        public int Code_pupil { get; set; }
        public string Name_pupil { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Father_name { get; set; }
        public string Mother_name { get; set; }
        public int Code_class { get; set; }
        public string Additional_information { get; set; }
    
        public virtual Classes Classes { get; set; }
    }
}
