//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Code_timetable { get; set; }
        public Nullable<System.DateTime> Date_lesson { get; set; }
        public string Day_week { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
        public Nullable<System.TimeSpan> End_time { get; set; }
        public int Code_class { get; set; }
        public int Code_lesson { get; set; }
        public int Code_employee { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Lessons Lessons { get; set; }
    }
}
