//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_rab_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_record
    {
        public int Code_list { get; set; }
        public Nullable<System.DateTime> Date_reception { get; set; }
        public Nullable<System.DateTime> Date_liberation { get; set; }
        public int Code_employee { get; set; }
        public int Code_post { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Post Post { get; set; }
    }
}
